/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package cz.fei.upce;

import cz.fei.upce.application.App;
import cz.fei.upce.injector.DependencyInjector;
import cz.fei.upce.service.NewsletterService;

public class NewsletterApp implements App {

    private NewsletterService newsletterService;

    public NewsletterApp(NewsletterService newsletterService) {
        this.newsletterService = newsletterService;
    }

    @Override
    public void process() {
        newsletterService.registerNewsLetting("ondrej.chrbolka@gmail.com");
    }

    public static void main(String[] args) {
        App app = DependencyInjector.getNewsletterApp();
        app.process();
    }
}
